# Generated by Django 4.2.30 on 2026-06-23 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('GYM', 'Gym / Weight Training'), ('CARDIO', 'Cardio / Running'), ('YOGA', 'Yoga / Flexibility'), ('SPORTS', 'Sports / Recreation'), ('REST', 'Active Rest / Recovery')], default='GYM', max_length=20)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Workout duration in minutes', null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive active days')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False, help_text='Intentional rest — does not break streak')),
                ('notes', models.TextField(blank=True, help_text='How did it feel? PRs hit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Log',
                'verbose_name_plural': 'Performance Logs',
                'ordering': ['-date_logged'],
            },
        ),
        migrations.CreateModel(
            name='TechLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('CODE', 'Coding / Development'), ('COURSE', 'Online Course / Tutorial'), ('PROJECT', 'Side Project Work'), ('READ', 'Technical Reading / Docs'), ('DSA', 'DSA / Interview Prep'), ('OSS', 'Open Source Contribution')], default='CODE', max_length=10)),
                ('topic', models.CharField(help_text='e.g., Django ORM, React Hooks, LeetCode #234', max_length=200)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Time spent (in minutes)', null=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='LeetCode-style consecutive coding days')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('github_committed', models.BooleanField(default=False, help_text='Did you push at least one commit today?')),
                ('notes', models.TextField(blank=True, help_text='Key takeaways, blockers, resources saved')),
                ('resources_url', models.URLField(blank=True, help_text='Link to course, article, or GitHub repo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tech Log',
                'verbose_name_plural': 'Tech Logs',
                'ordering': ['-date_logged'],
            },
        ),
        migrations.CreateModel(
            name='WealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('SIP', 'SIP / Mutual Fund Investment'), ('STOCK', 'Stock Trade / Action'), ('REVIEW', 'Portfolio Review'), ('STUDY', 'Financial Study / Research'), ('EXPENSE', 'Expense Audit')], default='SIP', max_length=10)),
                ('amount_invested', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in INR (₹)', max_digits=12, null=True)),
                ('instrument_name', models.CharField(blank=True, help_text='e.g., Nifty 50 Index Fund, HDFC Mid-Cap, Infosys', max_length=120)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive days with a wealth action')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('sip_completed', models.BooleanField(default=False, help_text='Was the scheduled SIP for today completed?')),
                ('notes', models.TextField(blank=True, help_text='Market observations, decisions, lessons learned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wealth Log',
                'verbose_name_plural': 'Wealth Logs',
                'ordering': ['-date_logged'],
            },
        ),
    ]
