# Generated by Django 4.2.30 on 2026-06-23 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('mood', models.CharField(choices=[('GREAT', '😄 Great'), ('GOOD', '🙂 Good'), ('OKAY', '😐 Okay'), ('LOW', '😔 Low'), ('STRESSED', '😤 Stressed')], default='GOOD', max_length=10)),
                ('energy_level', models.PositiveSmallIntegerField(default=5, help_text='Energy level 1 (exhausted) – 10 (amazing)')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours slept last night', max_digits=4, null=True)),
                ('highlights', models.TextField(blank=True, help_text='What went well today?')),
                ('learnings', models.TextField(blank=True, help_text='What did I learn today?')),
                ('challenges', models.TextField(blank=True, help_text='What was hard today?')),
                ('gratitude', models.TextField(blank=True, help_text='3 things I am grateful for')),
                ('tomorrow_goals', models.TextField(blank=True, help_text='Top 3 things to do tomorrow')),
                ('notes', models.TextField(blank=True, help_text='Free-form thoughts, ideas, anything')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Journal',
                'verbose_name_plural': 'Daily Journal Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('PERSONAL', 'Personal'), ('WORK', 'Work'), ('IDEAS', 'Ideas'), ('LEARNING', 'Learning'), ('HEALTH', 'Health'), ('FINANCE', 'Finance'), ('OTHER', 'Other')], default='PERSONAL', max_length=15)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. django,idea,project', max_length=300)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short bio about yourself')),
                ('avatar_url', models.URLField(blank=True, help_text='Link to a profile photo')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('short_term_goals', models.TextField(blank=True, help_text='Goals for the next 3–6 months')),
                ('long_term_goals', models.TextField(blank=True, help_text='Goals for 1–5 years ahead')),
                ('life_mission', models.TextField(blank=True, help_text='Your personal mission statement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profiles',
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='e.g. 2026-06-01 for June 2026', unique=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, help_text='Take-home / in-hand salary', max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, help_text='PF / ESI deducted', max_digits=10)),
                ('tax_deducted', models.DecimalField(decimal_places=2, default=0, help_text='TDS / income tax deducted', max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, help_text='Freelance, dividends, rent, etc.', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Record',
                'verbose_name_plural': 'Salary Records',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('RENT', 'Rent / Housing'), ('FOOD', 'Food & Groceries'), ('TRANSPORT', 'Transport'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health & Medical'), ('INVESTMENT', 'Investment / SIP'), ('EMI', 'EMI / Loan'), ('UTILITIES', 'Utilities & Bills'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_recurring', models.BooleanField(default=False, help_text='Monthly fixed expense (rent, EMI…)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.salaryrecord')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
