# Generated by Django 4.2.30 on 2026-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyjournal_note_personalprofile_salaryrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='life_mission',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='long_term_goals',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='short_term_goals',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='account_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='custom_vault',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value details'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='driving_license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Allergies, policy numbers, health info'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
