# Generated by Django 4.2.30 on 2026-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_personalprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
