# Generated by Django 4.2.30 on 2026-06-25 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_personalprofile_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Detailed content or answer')),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Total times reviewed')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revision Card',
                'verbose_name_plural': 'Revision Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload the PDF file to read in-app', null=True, upload_to='study_pdfs/')),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('READING', 'Currently Reading'), ('COMPLETED', 'Completed'), ('PLAN', 'Plan to Read')], default='PLAN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Document',
                'verbose_name_plural': 'Study Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('BOOK', 'Book Reading'), ('COURSE', 'Online Course / Video'), ('REVISION', 'Revision / Reviewing Cards'), ('PRACTICE', 'Practice / Labs')], default='BOOK', max_length=20)),
                ('topic', models.CharField(help_text='What topic did you learn today?', max_length=255)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Study duration in minutes', null=True)),
                ('pages_read', models.PositiveIntegerField(blank=True, help_text='Number of pages read (if reading a book)', null=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive study days')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Key takeaways, notes, or solutions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='Linked PDF document (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_logs', to='tracker.studydocument')),
            ],
            options={
                'verbose_name': 'Study Log',
                'verbose_name_plural': 'Study Logs',
                'ordering': ['-date_logged'],
            },
        ),
        migrations.DeleteModel(
            name='WealthLog',
        ),
    ]
