# Generated by Django 4.2.30 on 2026-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_revisioncard_studydocument_studylog_delete_wealthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
