# tracker/views.py
"""
DRF Views for Life OS Tracker.

Architecture:
  - ModelViewSet  →  full CRUD (list, create, retrieve, update, partial_update, destroy)
  - Custom @action →  /streak/    per-pillar streak summary
  - Custom @action →  /by-date/   filter logs for a specific date
  - DashboardView  →  single aggregate view across all pillars for today

Authentication: JWT (enforced via DEFAULT_AUTHENTICATION_CLASSES in settings)
Permissions:    IsAuthenticated (all endpoints require a valid token)
"""

from datetime import date as date_type
from django.utils import timezone

from rest_framework import viewsets, filters, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from django_filters.rest_framework import DjangoFilterBackend

from .models import PerformanceLog, StudyDocument, RevisionCard, StudyLog, TechLog, DailyJournal
from .serializers import (
    PerformanceLogSerializer,
    PerformanceLogSummarySerializer,
    StudyDocumentSerializer,
    RevisionCardSerializer,
    StudyLogSerializer,
    StudyLogSummarySerializer,
    TechLogSerializer,
    TechLogSummarySerializer,
    DashboardSerializer,
)
from .utils import calculate_streak


# ══════════════════════════════════════════════════════════════
# BASE MIXIN — shared behaviour for all pillar ViewSets
# ══════════════════════════════════════════════════════════════

class PillarViewSetMixin:
    """
    Mixin that:
      - Uses a Summary serializer for list actions (less data over the wire)
      - Uses the Full serializer for create/retrieve/update/delete
      - Adds a /streak/ custom action
      - Adds a /by-date/?date=YYYY-MM-DD custom action
    """
    permission_classes = [IsAuthenticated]

    # Subclasses must define these
    full_serializer_class    = None
    summary_serializer_class = None

    def get_serializer_class(self):
        if self.action == 'list':
            return self.summary_serializer_class
        return self.full_serializer_class

    @action(detail=False, methods=['get'], url_path='streak')
    def streak_summary(self, request):
        """
        GET /api/<pillar>/streak/
        Returns current streak (calculated live) and all-time longest streak.
        """
        model_class = self.queryset.model
        current     = calculate_streak(model_class)
        longest     = (
            model_class.objects
            .order_by('-longest_streak')
            .values_list('longest_streak', flat=True)
            .first() or 0
        )
        return Response({
            'pillar':          model_class.__name__,
            'current_streak':  current,
            'longest_streak':  longest,
        })

    @action(detail=False, methods=['get'], url_path='by-date')
    def by_date(self, request):
        """
        GET /api/<pillar>/by-date/?date=YYYY-MM-DD
        Returns all logs for the given date (defaults to today).
        """
        date_str = request.query_params.get('date', str(date_type.today()))
        try:
            target_date = date_type.fromisoformat(date_str)
        except ValueError:
            return Response(
                {'error': 'Invalid date format. Use YYYY-MM-DD.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        qs         = self.queryset.filter(date_logged=target_date)
        serializer = self.full_serializer_class(qs, many=True)
        return Response({
            'date':  str(target_date),
            'count': qs.count(),
            'results': serializer.data,
        })


# ══════════════════════════════════════════════════════════════
# PILLAR 1: PERFORMANCE
# ══════════════════════════════════════════════════════════════

class PerformanceLogViewSet(PillarViewSetMixin, viewsets.ModelViewSet):
    """
    Full CRUD for Performance (Fitness/Gym) logs.

    Endpoints auto-generated by DRF Router:
      GET    /api/performance/              → list (summary)
      POST   /api/performance/              → create
      GET    /api/performance/<id>/         → retrieve (full)
      PUT    /api/performance/<id>/         → update
      PATCH  /api/performance/<id>/         → partial update
      DELETE /api/performance/<id>/         → destroy

    Custom actions:
      GET    /api/performance/streak/       → streak summary
      GET    /api/performance/by-date/      → logs for a specific date
    """
    queryset                 = PerformanceLog.objects.all().order_by('-date_logged')
    full_serializer_class    = PerformanceLogSerializer
    summary_serializer_class = PerformanceLogSummarySerializer

    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = {
        'date_logged':   ['exact', 'gte', 'lte'],
        'activity_type': ['exact', 'in'],
        'is_rest_day':   ['exact'],
    }
    ordering_fields  = ['date_logged', 'current_streak', 'duration_mins', 'calories_burned']


# ══════════════════════════════════════════════════════════════
# PILLAR 2: WEALTH
# ══════════════════════════════════════════════════════════════

class StudyDocumentViewSet(viewsets.ModelViewSet):
    queryset = StudyDocument.objects.all().order_by('-updated_at')
    serializer_class = StudyDocumentSerializer
    permission_classes = [IsAuthenticated]


class RevisionCardViewSet(viewsets.ModelViewSet):
    queryset = RevisionCard.objects.all().order_by('-created_at')
    serializer_class = RevisionCardSerializer
    permission_classes = [IsAuthenticated]

    @action(detail=True, methods=['post'], url_path='review')
    def mark_reviewed(self, request, pk=None):
        card = self.get_object()
        card.review_count += 1
        card.last_reviewed = timezone.now().date()
        card.save()
        return Response({
            'status': 'reviewed',
            'review_count': card.review_count,
            'last_reviewed': str(card.last_reviewed)
        })


class StudyLogViewSet(PillarViewSetMixin, viewsets.ModelViewSet):
    """
    Full CRUD for Study (Books/Online Courses) logs.
    """
    queryset                 = StudyLog.objects.all().order_by('-date_logged')
    full_serializer_class    = StudyLogSerializer
    summary_serializer_class = StudyLogSummarySerializer

    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = {
        'date_logged':   ['exact', 'gte', 'lte'],
        'activity_type': ['exact', 'in'],
    }
    ordering_fields  = ['date_logged', 'current_streak', 'duration_mins']


# ══════════════════════════════════════════════════════════════
# PILLAR 3: TECH
# ══════════════════════════════════════════════════════════════

class TechLogViewSet(PillarViewSetMixin, viewsets.ModelViewSet):
    """
    Full CRUD for Tech (Coding/Learning) logs.

    Endpoints auto-generated by DRF Router:
      GET    /api/tech/                     → list (summary)
      POST   /api/tech/                     → create
      GET    /api/tech/<id>/                → retrieve (full)
      PUT    /api/tech/<id>/                → update
      PATCH  /api/tech/<id>/                → partial update
      DELETE /api/tech/<id>/                → destroy

    Custom actions:
      GET    /api/tech/streak/              → streak summary
      GET    /api/tech/by-date/             → logs for a specific date
    """
    queryset                 = TechLog.objects.all().order_by('-date_logged')
    full_serializer_class    = TechLogSerializer
    summary_serializer_class = TechLogSummarySerializer

    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = {
        'date_logged':       ['exact', 'gte', 'lte'],
        'category':          ['exact', 'in'],
        'github_committed':  ['exact'],
    }
    search_fields    = ['topic', 'notes']
    ordering_fields  = ['date_logged', 'current_streak', 'duration_mins']


# ══════════════════════════════════════════════════════════════
# DASHBOARD VIEW — Today's snapshot across all pillars
# ══════════════════════════════════════════════════════════════

class DashboardView(APIView):
    """
    GET /api/dashboard/
    Returns today's logs and live streaks for all three pillars.
    Requires authentication.

    Response shape:
    {
        "date": "2026-06-23",
        "performance": [...],
        "study": [...],
        "tech": [...],
        "streaks": {
            "performance": { "current": 5, "longest": 12 },
            "study":       { "current": 3, "longest": 8  },
            "tech":        { "current": 7, "longest": 30 }
        }
    }
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        today = date_type.today()

        perf_qs   = PerformanceLog.objects.filter(date_logged=today).order_by('-created_at')
        study_qs  = StudyLog.objects.filter(date_logged=today).order_by('-created_at')
        tech_qs   = TechLog.objects.filter(date_logged=today).order_by('-created_at')
        journal_exists = DailyJournal.objects.filter(date=today).exists()

        def streak_dict(model_class):
            return {
                'current': calculate_streak(model_class),
                'longest': model_class.objects.order_by('-longest_streak')
                           .values_list('longest_streak', flat=True)
                           .first() or 0,
            }

        payload = {
            'date':        str(today),
            'performance': PerformanceLogSummarySerializer(perf_qs, many=True).data,
            'study':       StudyLogSummarySerializer(study_qs, many=True).data,
            'tech':        TechLogSummarySerializer(tech_qs, many=True).data,
            'journal_written': journal_exists,
            'streaks': {
                'performance': streak_dict(PerformanceLog),
                'study':       streak_dict(StudyLog),
                'tech':        streak_dict(TechLog),
            }
        }
        return Response(payload, status=status.HTTP_200_OK)
